### ISSUE TITLE
MySQL GHA fails when using windows-latest for MySQL flexible server 

### ISSUE THREAD

**Issue by mksuni** [Azure/mysql#28]
Here is the GHA build log https://github.com/mksuni/wordpress-app-svc-linux/actions/runs/492898077 
![thumbnail_image](https://user-images.githubusercontent.com/3684166/105075899-398e5200-5a3f-11eb-8a68-68d5d71e8043.png)

**Comment by 20shivangi** [comment]
@mksuni Please have a look at the troubleshooting [guide](https://www.stackhero.io/en/documentations/mysql/getting-started#troubleshooting) if it is helpful for you.

**Comment by 20shivangi** [comment]
@mksuni Any update here ?

**Comment by 20shivangi** [comment]
Closing the issue since there has been no response for so long. Feel free to open the issue in case the troubleshooting doc is not helpful to you
